[package]
name = "spoke-chain-caller"
version.workspace = true
edition.workspace = true

[dependencies]
solver-common = { path = "../solver-common" }

tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true

