[package]
name = "spoke-chain-caller"
version.workspace = true
edition.workspace = true

[dependencies]
khalani-solver = { path = "../" }

tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true

