[package]
name = "cross-chain-market-maker"
version.workspace = true
edition.workspace = true

[dependencies]
solver-common = { path = "../solver-common" }

tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
