name: CI (Test , Docker , Publish)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  SEPOLIA_WS_URL: ${{ secrets.SEPOLIA_WS_URL }}
  FUJI_RPC_URL: ${{ secrets.FUJI_RPC_URL }}
  FUJI_WS_URL: ${{ secrets.FUJI_WS_URL }}
  CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      # - name: Run cargo tarpaulin
      #   uses: actions-rs/tarpaulin@v0.1
      #   with:
      #     version: 'v0.1.3'
      #     args: '--out Xml'

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

  # publish:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         override: true
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: publish
  #         args: --token ${{ secrets.CRATES_IO_TOKEN }}